// source: fabric/view_data.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var peer_proposal_response_pb = require('../peer/proposal_response_pb.js');
goog.object.extend(proto, peer_proposal_response_pb);
goog.exportSymbol('proto.fabric.view_data.FabricView', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fabric.view_data.FabricView = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fabric.view_data.FabricView.repeatedFields_, null);
};
goog.inherits(proto.fabric.view_data.FabricView, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fabric.view_data.FabricView.displayName = 'proto.fabric.view_data.FabricView';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fabric.view_data.FabricView.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fabric.view_data.FabricView.prototype.toObject = function(opt_includeInstance) {
  return proto.fabric.view_data.FabricView.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fabric.view_data.FabricView} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fabric.view_data.FabricView.toObject = function(includeInstance, msg) {
  var f, obj = {
    response: (f = msg.getResponse()) && peer_proposal_response_pb.Response.toObject(includeInstance, f),
    proposalResponsePayload: (f = msg.getProposalResponsePayload()) && peer_proposal_response_pb.ProposalResponsePayload.toObject(includeInstance, f),
    endorsementsList: jspb.Message.toObjectList(msg.getEndorsementsList(),
    peer_proposal_response_pb.Endorsement.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fabric.view_data.FabricView}
 */
proto.fabric.view_data.FabricView.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fabric.view_data.FabricView;
  return proto.fabric.view_data.FabricView.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fabric.view_data.FabricView} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fabric.view_data.FabricView}
 */
proto.fabric.view_data.FabricView.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new peer_proposal_response_pb.Response;
      reader.readMessage(value,peer_proposal_response_pb.Response.deserializeBinaryFromReader);
      msg.setResponse(value);
      break;
    case 3:
      var value = new peer_proposal_response_pb.ProposalResponsePayload;
      reader.readMessage(value,peer_proposal_response_pb.ProposalResponsePayload.deserializeBinaryFromReader);
      msg.setProposalResponsePayload(value);
      break;
    case 4:
      var value = new peer_proposal_response_pb.Endorsement;
      reader.readMessage(value,peer_proposal_response_pb.Endorsement.deserializeBinaryFromReader);
      msg.addEndorsements(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fabric.view_data.FabricView.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fabric.view_data.FabricView.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fabric.view_data.FabricView} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fabric.view_data.FabricView.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResponse();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      peer_proposal_response_pb.Response.serializeBinaryToWriter
    );
  }
  f = message.getProposalResponsePayload();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      peer_proposal_response_pb.ProposalResponsePayload.serializeBinaryToWriter
    );
  }
  f = message.getEndorsementsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      peer_proposal_response_pb.Endorsement.serializeBinaryToWriter
    );
  }
};


/**
 * optional protos.Response response = 1;
 * @return {?proto.protos.Response}
 */
proto.fabric.view_data.FabricView.prototype.getResponse = function() {
  return /** @type{?proto.protos.Response} */ (
    jspb.Message.getWrapperField(this, peer_proposal_response_pb.Response, 1));
};


/**
 * @param {?proto.protos.Response|undefined} value
 * @return {!proto.fabric.view_data.FabricView} returns this
*/
proto.fabric.view_data.FabricView.prototype.setResponse = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fabric.view_data.FabricView} returns this
 */
proto.fabric.view_data.FabricView.prototype.clearResponse = function() {
  return this.setResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fabric.view_data.FabricView.prototype.hasResponse = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional protos.ProposalResponsePayload proposal_response_payload = 3;
 * @return {?proto.protos.ProposalResponsePayload}
 */
proto.fabric.view_data.FabricView.prototype.getProposalResponsePayload = function() {
  return /** @type{?proto.protos.ProposalResponsePayload} */ (
    jspb.Message.getWrapperField(this, peer_proposal_response_pb.ProposalResponsePayload, 3));
};


/**
 * @param {?proto.protos.ProposalResponsePayload|undefined} value
 * @return {!proto.fabric.view_data.FabricView} returns this
*/
proto.fabric.view_data.FabricView.prototype.setProposalResponsePayload = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fabric.view_data.FabricView} returns this
 */
proto.fabric.view_data.FabricView.prototype.clearProposalResponsePayload = function() {
  return this.setProposalResponsePayload(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fabric.view_data.FabricView.prototype.hasProposalResponsePayload = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated protos.Endorsement endorsements = 4;
 * @return {!Array<!proto.protos.Endorsement>}
 */
proto.fabric.view_data.FabricView.prototype.getEndorsementsList = function() {
  return /** @type{!Array<!proto.protos.Endorsement>} */ (
    jspb.Message.getRepeatedWrapperField(this, peer_proposal_response_pb.Endorsement, 4));
};


/**
 * @param {!Array<!proto.protos.Endorsement>} value
 * @return {!proto.fabric.view_data.FabricView} returns this
*/
proto.fabric.view_data.FabricView.prototype.setEndorsementsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.protos.Endorsement=} opt_value
 * @param {number=} opt_index
 * @return {!proto.protos.Endorsement}
 */
proto.fabric.view_data.FabricView.prototype.addEndorsements = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.protos.Endorsement, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fabric.view_data.FabricView} returns this
 */
proto.fabric.view_data.FabricView.prototype.clearEndorsementsList = function() {
  return this.setEndorsementsList([]);
};


goog.object.extend(exports, proto.fabric.view_data);
