// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/interop_payload.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InteropPayload struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InteropPayload) Reset()         { *m = InteropPayload{} }
func (m *InteropPayload) String() string { return proto.CompactTextString(m) }
func (*InteropPayload) ProtoMessage()    {}
func (*InteropPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d35362ddb7d7853, []int{0}
}

func (m *InteropPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InteropPayload.Unmarshal(m, b)
}
func (m *InteropPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InteropPayload.Marshal(b, m, deterministic)
}
func (m *InteropPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InteropPayload.Merge(m, src)
}
func (m *InteropPayload) XXX_Size() int {
	return xxx_messageInfo_InteropPayload.Size(m)
}
func (m *InteropPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_InteropPayload.DiscardUnknown(m)
}

var xxx_messageInfo_InteropPayload proto.InternalMessageInfo

func (m *InteropPayload) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *InteropPayload) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*InteropPayload)(nil), "common.InteropPayload")
}

func init() { proto.RegisterFile("common/interop_payload.proto", fileDescriptor_7d35362ddb7d7853) }

var fileDescriptor_7d35362ddb7d7853 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0xcf, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x2f, 0x88, 0x2f, 0x48, 0xac, 0xcc, 0xc9,
	0x4f, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xc8, 0x2a, 0xb9, 0x70, 0xf1,
	0x79, 0x42, 0x14, 0x04, 0x40, 0xe4, 0x85, 0x24, 0xb8, 0xd8, 0xa1, 0x4a, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x78, 0x82, 0x60, 0x5c, 0x90, 0x4c, 0x62, 0x4a, 0x4a, 0x51, 0x6a, 0x71, 0xb1, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0x67, 0x10, 0x8c, 0xeb, 0x14, 0x18, 0xe5, 0x9f, 0x9e, 0x59, 0x92, 0x51, 0x9a,
	0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x9f, 0x51, 0x59, 0x90, 0x5a, 0x94, 0x93, 0x9a, 0x92, 0x9e, 0x5a,
	0xa4, 0x9b, 0x93, 0x98, 0x54, 0xac, 0x5f, 0x9e, 0x9a, 0x58, 0x96, 0x5a, 0xa4, 0x9b, 0x92, 0x53,
	0xa2, 0x0b, 0x75, 0x4d, 0x6a, 0x51, 0x62, 0x52, 0x66, 0x4e, 0x66, 0x49, 0xa5, 0x3e, 0xd4, 0x95,
	0x60, 0x57, 0x15, 0xeb, 0xa6, 0xe7, 0x43, 0x05, 0x92, 0xd8, 0xc0, 0x22, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0x28, 0x7f, 0xf7, 0xc7, 0x00, 0x00, 0x00,
}
