// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/membership.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Membership captures the members of an external entity such as a thing,
// person, organization or groups of entities such as networks
type Membership struct {
	SecurityDomain       string             `protobuf:"bytes,1,opt,name=securityDomain,proto3" json:"securityDomain,omitempty"`
	Members              map[string]*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Membership) Reset()         { *m = Membership{} }
func (m *Membership) String() string { return proto.CompactTextString(m) }
func (*Membership) ProtoMessage()    {}
func (*Membership) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12d9f9e232cdb42, []int{0}
}

func (m *Membership) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Membership.Unmarshal(m, b)
}
func (m *Membership) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Membership.Marshal(b, m, deterministic)
}
func (m *Membership) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Membership.Merge(m, src)
}
func (m *Membership) XXX_Size() int {
	return xxx_messageInfo_Membership.Size(m)
}
func (m *Membership) XXX_DiscardUnknown() {
	xxx_messageInfo_Membership.DiscardUnknown(m)
}

var xxx_messageInfo_Membership proto.InternalMessageInfo

func (m *Membership) GetSecurityDomain() string {
	if m != nil {
		return m.SecurityDomain
	}
	return ""
}

func (m *Membership) GetMembers() map[string]*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

// Member of a security group is represented by a set of public keys,
// certificates or certificate authorities
type Member struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Chain                []string `protobuf:"bytes,3,rep,name=chain,proto3" json:"chain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_a12d9f9e232cdb42, []int{1}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Member) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Member) GetChain() []string {
	if m != nil {
		return m.Chain
	}
	return nil
}

func init() {
	proto.RegisterType((*Membership)(nil), "common.Membership")
	proto.RegisterMapType((map[string]*Member)(nil), "common.Membership.MembersEntry")
	proto.RegisterType((*Member)(nil), "common.Member")
}

func init() { proto.RegisterFile("common/membership.proto", fileDescriptor_a12d9f9e232cdb42) }

var fileDescriptor_a12d9f9e232cdb42 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x69, 0xab, 0x95, 0x9d, 0x95, 0x45, 0x82, 0x60, 0xf1, 0x62, 0x59, 0x44, 0x7a, 0x69,
	0x0b, 0xeb, 0x45, 0x3d, 0x8a, 0x82, 0x08, 0x22, 0xf6, 0xe8, 0xad, 0xed, 0x0e, 0x6d, 0x30, 0x69,
	0x42, 0x9a, 0xae, 0xe4, 0xb3, 0xf9, 0xe5, 0x24, 0x4d, 0xeb, 0x9f, 0xbd, 0xbd, 0x79, 0xef, 0xe5,
	0x37, 0x64, 0xe0, 0xac, 0x16, 0x9c, 0x8b, 0x2e, 0xe7, 0xc8, 0x2b, 0x54, 0x7d, 0x4b, 0x65, 0x26,
	0x95, 0xd0, 0x82, 0x84, 0x2e, 0x58, 0x7f, 0x79, 0x00, 0x2f, 0x3f, 0x21, 0xb9, 0x82, 0x55, 0x8f,
	0xf5, 0xa0, 0xa8, 0x36, 0x0f, 0x82, 0x97, 0xb4, 0x8b, 0xbc, 0xd8, 0x4b, 0x16, 0xc5, 0x9e, 0x4b,
	0x6e, 0xe1, 0x68, 0x42, 0x46, 0x7e, 0x1c, 0x24, 0xcb, 0xcd, 0x45, 0xe6, 0x80, 0xd9, 0x2f, 0x6c,
	0x96, 0x8f, 0x9d, 0x56, 0xa6, 0x98, 0xfb, 0xe7, 0xcf, 0x70, 0xfc, 0x37, 0x20, 0x27, 0x10, 0x7c,
	0xa0, 0x99, 0xf6, 0x58, 0x49, 0x2e, 0xe1, 0x70, 0x57, 0xb2, 0x01, 0x23, 0x3f, 0xf6, 0x92, 0xe5,
	0x66, 0xf5, 0x1f, 0x5d, 0xb8, 0xf0, 0xce, 0xbf, 0xf1, 0xd6, 0x4f, 0x10, 0x3a, 0x93, 0x9c, 0xce,
	0x6f, 0x1c, 0xc7, 0x0d, 0x84, 0xc0, 0x81, 0x36, 0xd2, 0x81, 0x16, 0xc5, 0xa8, 0x6d, 0xb3, 0x6e,
	0xed, 0xcf, 0x82, 0x38, 0xb0, 0xcd, 0x71, 0xb8, 0x7f, 0x7b, 0x7f, 0x6d, 0xa8, 0x6e, 0x87, 0xca,
	0x2e, 0xcb, 0x5b, 0x23, 0x51, 0x31, 0xdc, 0x36, 0xa8, 0x52, 0x56, 0x56, 0x7d, 0xfe, 0x89, 0xe5,
	0x0e, 0x55, 0xba, 0x65, 0x3a, 0xa5, 0x9d, 0x46, 0x25, 0x24, 0xaa, 0xb2, 0xa2, 0x8c, 0x6a, 0x93,
	0x4f, 0x27, 0x1e, 0xef, 0xda, 0xa7, 0x8d, 0x98, 0x8c, 0x2a, 0x1c, 0x9d, 0xeb, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x3f, 0x4c, 0xac, 0xb0, 0x84, 0x01, 0x00, 0x00,
}
