// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/proofs.proto

package common

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Proof struct {
	Signature            string   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Certificate          string   `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proof) Reset()         { *m = Proof{} }
func (m *Proof) String() string { return proto.CompactTextString(m) }
func (*Proof) ProtoMessage()    {}
func (*Proof) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5d7dbebb285af4, []int{0}
}

func (m *Proof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proof.Unmarshal(m, b)
}
func (m *Proof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proof.Marshal(b, m, deterministic)
}
func (m *Proof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proof.Merge(m, src)
}
func (m *Proof) XXX_Size() int {
	return xxx_messageInfo_Proof.Size(m)
}
func (m *Proof) XXX_DiscardUnknown() {
	xxx_messageInfo_Proof.DiscardUnknown(m)
}

var xxx_messageInfo_Proof proto.InternalMessageInfo

func (m *Proof) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Proof) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

type Proofs struct {
	Proofs               []*Proof `protobuf:"bytes,1,rep,name=proofs,proto3" json:"proofs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proofs) Reset()         { *m = Proofs{} }
func (m *Proofs) String() string { return proto.CompactTextString(m) }
func (*Proofs) ProtoMessage()    {}
func (*Proofs) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb5d7dbebb285af4, []int{1}
}

func (m *Proofs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proofs.Unmarshal(m, b)
}
func (m *Proofs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proofs.Marshal(b, m, deterministic)
}
func (m *Proofs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proofs.Merge(m, src)
}
func (m *Proofs) XXX_Size() int {
	return xxx_messageInfo_Proofs.Size(m)
}
func (m *Proofs) XXX_DiscardUnknown() {
	xxx_messageInfo_Proofs.DiscardUnknown(m)
}

var xxx_messageInfo_Proofs proto.InternalMessageInfo

func (m *Proofs) GetProofs() []*Proof {
	if m != nil {
		return m.Proofs
	}
	return nil
}

func init() {
	proto.RegisterType((*Proof)(nil), "common.Proof")
	proto.RegisterType((*Proofs)(nil), "common.Proofs")
}

func init() { proto.RegisterFile("common/proofs.proto", fileDescriptor_bb5d7dbebb285af4) }

var fileDescriptor_bb5d7dbebb285af4 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0xb1, 0x6a, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0xdc, 0x52, 0x41, 0x14, 0xba, 0xa8, 0x8b, 0x87, 0x0e, 0x26, 0x50, 0xc8, 0x22,
	0x0b, 0xda, 0x37, 0xe8, 0xd2, 0xb1, 0x6d, 0xc6, 0x6e, 0x92, 0x73, 0x51, 0x04, 0xb2, 0x4f, 0x9c,
	0xce, 0x2d, 0x7e, 0xfb, 0x62, 0xd9, 0xe0, 0xac, 0xbf, 0x3f, 0xdc, 0xc7, 0xc9, 0xa7, 0x0e, 0xfb,
	0x1e, 0x07, 0x93, 0x08, 0xf1, 0x92, 0xdb, 0x44, 0xc8, 0xa8, 0xc4, 0x82, 0x87, 0x0f, 0xf9, 0xf0,
	0x35, 0xbb, 0x7a, 0x96, 0xbb, 0x1c, 0xfc, 0x60, 0x79, 0x24, 0xa8, 0xab, 0xa6, 0x3a, 0xee, 0x4e,
	0x1b, 0xa8, 0x46, 0xee, 0x3b, 0x20, 0x0e, 0x97, 0xd0, 0x59, 0x86, 0xfa, 0xae, 0xf4, 0x5b, 0x3a,
	0x18, 0x29, 0xca, 0xa1, 0xac, 0x5e, 0xa4, 0x58, 0xa6, 0xea, 0xaa, 0xb9, 0x3f, 0xee, 0x5f, 0x1f,
	0xdb, 0x65, 0xab, 0x2d, 0xfd, 0xb4, 0xc6, 0xf7, 0xef, 0x9f, 0x4f, 0x1f, 0xf8, 0x3a, 0xba, 0x39,
	0x9b, 0xeb, 0x94, 0x80, 0x22, 0x9c, 0x3d, 0x90, 0x8e, 0xd6, 0x65, 0xf3, 0x07, 0xf6, 0x17, 0x48,
	0x9f, 0x23, 0xeb, 0x30, 0x30, 0x10, 0x26, 0x20, 0xeb, 0x42, 0x0c, 0x3c, 0x99, 0xed, 0x21, 0xc6,
	0xac, 0x3d, 0xae, 0xe0, 0x44, 0x91, 0xb7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0x73, 0xf3,
	0xbb, 0xf2, 0x00, 0x00, 0x00,
}
