name = "Corda_Relay"
port="9081"
host="localhost"
hostname="localhost"
db_path="db/Corda_Relay/requests"
# This will be replaced by the task queue.
remote_db_path="db/Corda_Relay/remote_request"

[networks]
[networks.Corda_Network]
network="Corda"
[networks.Dummy_Network]
network="Dummy"
[networks.americantfn]
network="Corda"

[relays]
[relays.Fabric_Relay]
hostname="localhost"
port="9080"
[relays.wtln_relay]
hostname="tradelens.sl.cloud9.ibm.com"
port="9089"
[relays.Dummy_relay]
hostname="localhost"
port="9085"
[relays.Corda_Relay2]
hostname="localhost"
port="9080"

[drivers]
[drivers.Fabric]
hostname="localhost"
port="9093"
[drivers.Corda]
hostname="localhost"
port="9099"
[drivers.Dummy]
hostname="localhost"
port="9095"
