// Code generated by protoc-gen-go. DO NOT EDIT.
// source: corda/view_data.proto

package corda

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ViewData struct {
	Notarizations []*ViewData_Notarization `protobuf:"bytes,1,rep,name=notarizations,proto3" json:"notarizations,omitempty"`
	// Bytes of InteropPayload
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewData) Reset()         { *m = ViewData{} }
func (m *ViewData) String() string { return proto.CompactTextString(m) }
func (*ViewData) ProtoMessage()    {}
func (*ViewData) Descriptor() ([]byte, []int) {
	return fileDescriptor_af517aa8195ed26f, []int{0}
}

func (m *ViewData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewData.Unmarshal(m, b)
}
func (m *ViewData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewData.Marshal(b, m, deterministic)
}
func (m *ViewData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewData.Merge(m, src)
}
func (m *ViewData) XXX_Size() int {
	return xxx_messageInfo_ViewData.Size(m)
}
func (m *ViewData) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewData.DiscardUnknown(m)
}

var xxx_messageInfo_ViewData proto.InternalMessageInfo

func (m *ViewData) GetNotarizations() []*ViewData_Notarization {
	if m != nil {
		return m.Notarizations
	}
	return nil
}

func (m *ViewData) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ViewData_Notarization struct {
	Signature            string   `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Certificate          string   `protobuf:"bytes,2,opt,name=certificate,proto3" json:"certificate,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ViewData_Notarization) Reset()         { *m = ViewData_Notarization{} }
func (m *ViewData_Notarization) String() string { return proto.CompactTextString(m) }
func (*ViewData_Notarization) ProtoMessage()    {}
func (*ViewData_Notarization) Descriptor() ([]byte, []int) {
	return fileDescriptor_af517aa8195ed26f, []int{0, 0}
}

func (m *ViewData_Notarization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewData_Notarization.Unmarshal(m, b)
}
func (m *ViewData_Notarization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewData_Notarization.Marshal(b, m, deterministic)
}
func (m *ViewData_Notarization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewData_Notarization.Merge(m, src)
}
func (m *ViewData_Notarization) XXX_Size() int {
	return xxx_messageInfo_ViewData_Notarization.Size(m)
}
func (m *ViewData_Notarization) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewData_Notarization.DiscardUnknown(m)
}

var xxx_messageInfo_ViewData_Notarization proto.InternalMessageInfo

func (m *ViewData_Notarization) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *ViewData_Notarization) GetCertificate() string {
	if m != nil {
		return m.Certificate
	}
	return ""
}

func (m *ViewData_Notarization) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*ViewData)(nil), "corda.ViewData")
	proto.RegisterType((*ViewData_Notarization)(nil), "corda.ViewData.Notarization")
}

func init() { proto.RegisterFile("corda/view_data.proto", fileDescriptor_af517aa8195ed26f) }

var fileDescriptor_af517aa8195ed26f = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x49, 0x8a, 0x7f, 0xb2, 0xad, 0x1e, 0x16, 0x84, 0x20, 0x3d, 0x04, 0x4f, 0xb9, 0x24,
	0x0b, 0xfa, 0x06, 0xc5, 0x73, 0x91, 0x1c, 0x3c, 0x78, 0x50, 0x26, 0xd9, 0x31, 0x1d, 0x48, 0x76,
	0xc2, 0x66, 0xda, 0x10, 0x9f, 0xd0, 0xc7, 0x12, 0x16, 0x8a, 0xe9, 0x71, 0x7e, 0xf3, 0xfb, 0x06,
	0xe6, 0x53, 0x0f, 0x0d, 0x7b, 0x0b, 0xe6, 0x44, 0x38, 0x7d, 0x59, 0x10, 0x28, 0x07, 0xcf, 0xc2,
	0xfa, 0x2a, 0xe0, 0xa7, 0xdf, 0x48, 0xdd, 0xbe, 0x13, 0x4e, 0xaf, 0x20, 0xa0, 0x77, 0xea, 0xce,
	0xb1, 0x80, 0xa7, 0x1f, 0x10, 0x62, 0x37, 0xa6, 0x51, 0xb6, 0xca, 0xd7, 0xcf, 0xdb, 0x32, 0xb8,
	0xe5, 0xd9, 0x2b, 0xf7, 0x0b, 0xa9, 0xba, 0x8c, 0xe8, 0x54, 0xdd, 0x0c, 0x30, 0x77, 0x0c, 0x36,
	0x8d, 0xb3, 0x28, 0xdf, 0x54, 0xe7, 0xf1, 0xf1, 0x53, 0x6d, 0x96, 0x41, 0xbd, 0x55, 0xc9, 0x48,
	0xad, 0x03, 0x39, 0x7a, 0x4c, 0xa3, 0x2c, 0xca, 0x93, 0xea, 0x1f, 0xe8, 0x4c, 0xad, 0x1b, 0xf4,
	0x42, 0xdf, 0xd4, 0x80, 0x60, 0xb8, 0x95, 0x54, 0x4b, 0xa4, 0xef, 0x55, 0x4c, 0x36, 0x5d, 0x85,
	0x45, 0x4c, 0x76, 0xf7, 0xf6, 0xb1, 0x6f, 0x49, 0x0e, 0xc7, 0xba, 0x6c, 0xb8, 0x37, 0x87, 0x79,
	0x40, 0xdf, 0xa1, 0x6d, 0xd1, 0x17, 0x1d, 0xd4, 0xa3, 0x99, 0x10, 0x4e, 0xe8, 0x0b, 0xdb, 0x49,
	0x41, 0x4e, 0xd0, 0xf3, 0x80, 0x1e, 0x6a, 0xea, 0x48, 0x66, 0xd3, 0x70, 0xdf, 0xb3, 0x33, 0xa1,
	0x99, 0xb1, 0x68, 0xd9, 0x84, 0x87, 0xeb, 0xeb, 0x00, 0x5e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x36, 0x41, 0x2f, 0x57, 0x43, 0x01, 0x00, 0x00,
}
