# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: CC-BY-4.0

name: Unit Test Fabric Interop CC and Sample Chaincode

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test_interopcc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'
        
    - name: Vendor
      run: make run-vendor
      working-directory: core/network/fabric-interop-cc/contracts/interop
      
    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/contracts/interop

    - name: Test
      run: go test -v ./...
      working-directory: core/network/fabric-interop-cc/contracts/interop

  test_assetmgmt:
    # if: ${{ false }}  # disable
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'
        
    - name: Vendor
      run: make run-vendor
      working-directory: core/network/fabric-interop-cc/interfaces/asset-mgmt

    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/interfaces/asset-mgmt

    - name: Test
      run: go test -v ./...
      working-directory: core/network/fabric-interop-cc/interfaces/asset-mgmt
      
  build_test_libs_utils:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: core/network/fabric-interop-cc/libs/utils

    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/libs/utils
      
  build_test_libs_assetexchange:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: core/network/fabric-interop-cc/libs/assetexchange

    - name: Build
      run: go build -v ./...
      working-directory: core/network/fabric-interop-cc/libs/assetexchange
      
  unit_test_sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: sdks/fabric/go-sdk

    - name: Build
      run: make build
      working-directory: sdks/fabric/go-sdk

    - name: Test
      run: make test
      working-directory: sdks/fabric/go-sdk
      
  build_test_cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v4.0.0
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: samples/fabric/go-cli

    - name: Build
      run: make build
      working-directory: samples/fabric/go-cli

  test_simplestate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: samples/fabric/simplestate

    - name: Build
      run: go build -v ./...
      working-directory: samples/fabric/simplestate

    - name: Test
      run: go test -v ./...
      working-directory: samples/fabric/simplestate
 
  test_simpleasset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: samples/fabric/simpleasset

    - name: Build
      run: go build -v ./...
      working-directory: samples/fabric/simpleasset

    - name: Test
      run: go test -v ./...
      working-directory: samples/fabric/simpleasset

  test_simpleassetandinterop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: samples/fabric/simpleassetandinterop

    - name: Build
      run: go build -v ./...
      working-directory: samples/fabric/simpleassetandinterop

    - name: Test
      run: go test -v ./...
      working-directory: samples/fabric/simpleassetandinterop

  test_simpleassettransfer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.20.2'

    - name: Vendor
      run: make run-vendor
      working-directory: samples/fabric/simpleassettransfer

    - name: Build
      run: go build -v ./...
      working-directory: samples/fabric/simpleassettransfer

    - name: Test
      run: go test -v ./...
      working-directory: samples/fabric/simpleassettransfer
